[General]
serversUrl=servers.ini
discordUrl=https://discord.gg/yxkVn4wBad

# Auto-load from gameresBaseUrl (CDN load) without showing the import dialog.
autoLoadGameRes=yes
gameresBaseUrl=//stdres.wangerhuoda.cn/
mapsBaseUrl=//gmap.wangerhuoda.cn/map/
modsBaseUrl=//gmap.wangerhuoda.cn/mod/
musicBaseUrl=//stdres.wangerhuoda.cn/music/
gameResArchiveUrl=https://download.ra2web.com/full-pack.7z

# Wang Er Huo Da site content overlay.
defaultFullyPackUrl=
patchNotesUrl=/patch-notes.html
breakingNewsUrl=/breaking-news.html
ladderRulesUrl=//www.ra2web.com/ladder-rules.html
modSdkUrl=https://github.com/ra2web/mod-sdk
donateUrl="//ra2web.com/#donate"
oldClientsBaseUrl=/old/
quickMatchEnabled=yes
unrankedQueueEnabled=yes
botsEnabled=yes
debugLogging=wol
debugGameState=yes

# Chronodivide 中国大区专供.
defaultLanguage=zh-CN
forcedModId=gonghui
viewport.width=1024
viewport.height=768

[CorsProxy]
archive.org="https://game.chronodivide.com/cors-proxy/?url="
